name: blog-panel

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: blog_dev_user
      POSTGRES_PASSWORD: dev_password1234
      POSTGRES_DB: blog_panel_dev
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:8080"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/app.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:4000

volumes:
  db_data:
